config/routes.rb
Rails.application.routes.draw do
  # 管理者用のルーティング
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  # 一般ユーザー用のルーティング
  scope module: :public do
    devise_for :users, controllers: {
      sessions: 'public/sessions',
      registrations: 'public/registrations',
      passwords: 'public/passwords'
    }
    
    # 一般ユーザーのトップページや情報
    root to: 'homes#top'
    get 'homes/about', to: 'homes#about', as: :about

    # ユーザー関連のルーティング
    resources :users, only: [:index, :show, :update, :edit, :destroy] do
      get 'mypage', on: :collection
    end

    # 検索機能のルーティング
    get 'search', to: 'searches#index', as: 'search'

    # レシピに関連するルーティング
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true
  
  has_one_attached :image  # 画像を追加
  has_many :comments, dependent: :destroy

  # 画像を取得するメソッドを追加
  def get_recipe_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    else
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        

        has_one_attached :profile_image
        has_many :recipes, dependent: :destroy
        has_many :comments, dependent: :destroy

        validates :name, presence: true
        validates :email, presence: true

        def get_profile_image(width, height)
          if profile_image.attached?
            profile_image.variant(resize_to_fill: [width, height]).processed
          else
            'no_image.png'
          end
        end
      end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin' 
  before_action :authenticate_admin!
  def index
      @users = User.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout 'admin'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def after_sign_in_path_for(resource)
    admin_dashboards_path # ログイン後にリダイレクトするパス
  end

   def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path # ログアウト後にリダイレクトするパス
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
# app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

private

def admin_controller?
  self.class.module_parent_name == 'Admin'
end

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def new
    @recipe = Recipe.new
  end

  def index
    @user = current_user
    @recipes = Recipe.all
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @newrecipe = Recipe.new
    @user = @recipe.user
  end

  def edit
    @recipe = Recipe.find(params[:id]) 
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      flash[:notice]="レシピが投稿されました"
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'レシピが更新されました'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]) 
    @recipe.destroy
    redirect_to mypage_path, notice: 'レシピを削除しました'
  end

  private

  def ensure_correct_user
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: "他人のレシピは編集できません。"
    end
  end

  def recipe_params
    params.require(:recipe).permit(:title, :body, :image, :ingredients, :instructions)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    # 初期化
    @users = []
    @recipes = []

    # ユーザー検索
    if params[:model] == 'user' && params[:keyword].present?
      @users = User.where('name LIKE ?', "%#{params[:keyword]}%")
    # レシピ検索
    elsif params[:model] == 'recipe' && params[:keyword].present?
      @recipes = Recipe.where('title LIKE ?', "%#{params[:keyword]}%")
    end
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">全ユーザー一覧</h1>
  <div class="list-group">
    <% @users.each do |user| %>
      <div class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <strong><%= user.name %></strong> - <%= user.email %>
        </div>
        <div>
          <!-- 詳細へのリンク -->
          <%= link_to '詳細', admin_user_path(user), class: 'btn btn-sm btn-primary ms-2' %>
          <!-- 削除リンク -->
          <%= link_to '削除', admin_user_path(user), 
                      method: :delete, 
                      data: { confirm: '本当に削除しますか？' }, 
                      class: 'btn btn-sm btn-danger ms-2' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<h1 class="mb-4">
Welcome to <i class="fas fa-cookie-bite text-warning"></i> <strong>Okashi_Lab</strong>!!
</h1>

app/views/homes/top.html.erb
<div class="container mt-5 text-center">
  <h1 class="mb-4">
    Welcome to <i class="fas fa-cookie-bite text-warning"></i> <strong>Okashi_Lab</strong>!!
  </h1>

  <p class="lead">
    <strong>Okashi_Lab</strong>は、<br>
    あなたのお菓子作りのレシピや感想を<br>
    気軽にシェアできるコミュニティサイトです🍰
  </p>

  <p class="mb-4">
    美味しいレシピを投稿したり、<br>
    他の人のレシピにコメントして一緒に楽しみましょう！
  </p>

  <div class="d-flex justify-content-center gap-3">
    <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/searches/index.html.erb
<div class="container mt-5">

  <% if params[:model] == 'user' && @users.any? %>
    <h3 class="mb-4">ユーザー検索結果</h3>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th>名前</th>
            <th>投稿数</th>
            <th>登録日</th>
            <th>プロフィール</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.recipes.count %></td>
              <td><%= user.created_at.strftime("%Y/%m/%d") %></td>
              <td><%= link_to 'プロフィール', user_path(user), class: "btn btn-sm btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% elsif params[:model] == 'user' %>
    <p>ユーザーに該当する検索結果はありません。</p>
  <% end %>

  <% if params[:model] == 'recipe' && @recipes.any? %>
    <h3 class="mb-4">レシピ検索結果</h3>
    <table class="table table-striped align-middle">
      <thead class="table-dark">
        <tr>
          <th>ユーザー</th>
          <th>タイトル</th>
          <th>紹介文</th>
        </tr>
      </thead>
      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <td>
              <%= link_to user_path(recipe.user_id) do %>
                <% begin %>
                  <%= image_tag recipe.get_recipe_image(80, 80), class: "rounded-circle border", alt: "レシピ画像", width: 80, height: 80 %>
                <% rescue => e %>
                  <%= image_tag 'no_image.png', class: "rounded-circle border", alt: "画像なし", width: 80, height: 80 %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to recipe_path(recipe.id), class: "text-decoration-none fw-bold" do %>
                <%= recipe.title %>
              <% end %>
            </td>
            <td><%= truncate(recipe.body, length: 100) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% elsif params[:model] == 'recipe' %>
    <p>レシピに該当する検索結果はありません。</p>
  <% end %>

</div>