config/routes.rb
Rails.application.routes.draw do
  # 管理者用のルーティング
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  # 一般ユーザー用のルーティング
  scope module: :public do
    devise_for :users, controllers: {
      sessions: 'public/sessions',
      registrations: 'public/registrations',
      passwords: 'public/passwords'
    }
    
    # 一般ユーザーのトップページや情報
    root to: 'homes#top'
    get 'homes/about', to: 'homes#about', as: :about

    # ユーザー関連のルーティング
    resources :users, only: [:index, :show, :update, :edit, :destroy] do
      get 'mypage', on: :collection
    end

    # 検索機能のルーティング
    get 'search', to: 'searches#index', as: 'search'

    # レシピに関連するルーティング
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true
  
  has_one_attached :image  # 画像を追加
  has_many :comments, dependent: :destroy

  # 画像を取得するメソッドを追加
  def get_recipe_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    else
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        

        has_one_attached :profile_image
        has_many :recipes, dependent: :destroy
        has_many :comments, dependent: :destroy

        validates :name, presence: true
        validates :email, presence: true

        def get_profile_image(width, height)
          if profile_image.attached?
            profile_image.variant(resize_to_fill: [width, height]).processed
          else
            'no_image.png'
          end
        end
      end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout 'admin'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def after_sign_in_path_for(resource)
    admin_dashboards_path # ログイン後にリダイレクトするパス
  end

   def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path # ログアウト後にリダイレクトするパス
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
# app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

private

def admin_controller?
  self.class.module_parent_name == 'Admin'
end

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def new
    @recipe = Recipe.new
  end

  def index
    @user = current_user
    @recipes = Recipe.all
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @newrecipe = Recipe.new
    @user = @recipe.user
  end

  def edit
    @recipe = Recipe.find(params[:id]) 
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      flash[:notice]="レシピが投稿されました"
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'レシピが更新されました'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]) 
    @recipe.destroy
    redirect_to mypage_path, notice: 'レシピを削除しました'
  end

  private

  def ensure_correct_user
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: "他人のレシピは編集できません。"
    end
  end

  def recipe_params
    params.require(:recipe).permit(:title, :body, :image, :ingredients, :instructions)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    # 初期化
    @users = []
    @recipes = []

    # ユーザー検索
    if params[:model] == 'user' && params[:keyword].present?
      @users = User.where('name LIKE ?', "%#{params[:keyword]}%")
    # レシピ検索
    elsif params[:model] == 'recipe' && params[:keyword].present?
      @recipes = Recipe.where('title LIKE ?', "%#{params[:keyword]}%")
    end
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %> <!-- ログインしている時だけ表示 -->

  <%= form_with url: search_path, method: :get, local: true do |form| %>
    
    <%= form.text_field :keyword, placeholder: "検索ワードを入力" %>
    <%= form.select :model, options_for_select([['ユーザー', 'user'], ['レシピ', 'recipe']]) %>
    <%= form.select :search_type, options_for_select([['部分一致', 'partial'], ['完全一致', 'exact']]) %>
    <%= form.submit "検索" %>
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OkashiLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/854d1847dd.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
  <header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Okashi_Lab', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to mypage_users_path, class: "nav-link" do %>
              <i class="fas fa-home"></i> Mypage
            <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to recipes_path, class: "nav-link" do %>
                <i class="fas fa-book-open"></i> Recipes
              <% end %>
            </li>
              <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                  <i class="fas fa-link"></i> Log out
                <% end %>
              </li>
                <% else %>
              <li class="nav-item">
                  <%= link_to root_path, class: "nav-link" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
                <li class="nav-item">
                  <%= link_to about_path, class: "nav-link" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                  <li class="nav-item">
                    <%= link_to new_user_registration_path, class: "nav-link" do %>
                      <i class="fas fa-user-plus"></i> Sign up
                    <% end %>
                  </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
             </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="row w-100 justify-content-center">
        <div class="col-md-8">
          <%= render 'layouts/header' %>
        </div>
      </div>
    <main class="flex-grow-1 container mt-4">
      <%= yield %>
    </main>
    <footer class="bg-dark text-white text-center py-3 mt-5">
      <div class="container">
        <p class="mb-0">©Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>